# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
kotlin.daemon.jvmargs=-Xmx2048m -XX:+UseParallelGC

# Android & Kotlin settings
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.enableBuiltInKotlin=true
android.javaCompile.suppressSourceTargetDeprecationWarning=true
